services:
  - type: web
    name: copartbr
    env: python
    buildCommand: pip install -r requirements.txt
      bash build.sh
    startCommand: python scraper.py
      python manage.py migrate &&
      gunicorn copart_clone.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: copart_clone.settings
      - key: PYTHON_VERSION
        value: 3.10.8