services:
  - type: web
    name: copart-clone
    env: python
    buildCommand: |
      bash build.sh
    startCommand: |
      python manage.py migrate &&
      gunicorn copart_clone.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: copart_clone.settings
      - key: PYTHON_VERSION
        value: 3.10
