services:
  - type: web
    name: copart-clone
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      export PYTHONPATH="${PYTHONPATH}:/opt/render/project/src"
      python manage.py migrate
      gunicorn copart_clone.wsgi:application --bind 0.0.0.0:$PORT