services:
  - type: web
    name: copart-clone
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
      playwright install --with-deps
    startCommand: |
      python scraper.py &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn copart_clone.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: copart_clone.settings
      - key: PYTHON_VERSION
        value: 3.10
